FROM node:18-alpine
WORKDIR /var/www/html
# No desenvolvimento, o npm install geralmente é feito na máquina host 
# ou via 'docker exec' para os arquivos aparecerem na sua pasta 'src'
EXPOSE 3000
CMD ["sh"]